//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger2BlogML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blogger2BlogML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching comment &apos;{0}&apos; to post &apos;{1}&apos;.
        /// </summary>
        internal static string Converter_AttachingComment {
            get {
                return ResourceManager.GetString("Converter_AttachingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger ATOM export file must exist.
        /// </summary>
        internal static string Converter_BloggerExportMissing {
            get {
                return ResourceManager.GetString("Converter_BloggerExportMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger ATOM export file path must be provided.
        /// </summary>
        internal static string Converter_BloggerExportNull {
            get {
                return ResourceManager.GetString("Converter_BloggerExportNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory containing BlogML export file path must exist.
        /// </summary>
        internal static string Converter_BlogMLPathMissing {
            get {
                return ResourceManager.GetString("Converter_BlogMLPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlogML export file path must be provided.
        /// </summary>
        internal static string Converter_BlogMLPathNull {
            get {
                return ResourceManager.GetString("Converter_BlogMLPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building BlogML....
        /// </summary>
        internal static string Converter_BuildingBlogML {
            get {
                return ResourceManager.GetString("Converter_BuildingBlogML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing comment - {0}.
        /// </summary>
        internal static string Converter_ImportingComment {
            get {
                return ResourceManager.GetString("Converter_ImportingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing post - {0}.
        /// </summary>
        internal static string Converter_ImportingPost {
            get {
                return ResourceManager.GetString("Converter_ImportingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting: {0} = {1}.
        /// </summary>
        internal static string Converter_ImportingSettings {
            get {
                return ResourceManager.GetString("Converter_ImportingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author is {0} ({1}) - {2}.
        /// </summary>
        internal static string Converter_MessageBlogAuthor {
            get {
                return ResourceManager.GetString("Converter_MessageBlogAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}, last updated {1}.
        /// </summary>
        internal static string Converter_MessageBlogTitle {
            get {
                return ResourceManager.GetString("Converter_MessageBlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Unexpected category scheme: {0}.
        /// </summary>
        internal static string Converter_MessageUnexpectedCategoryScheme {
            get {
                return ResourceManager.GetString("Converter_MessageUnexpectedCategoryScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Unexpected entry kind: {0}.
        /// </summary>
        internal static string Converter_MessageUnexpectedEntryKind {
            get {
                return ResourceManager.GetString("Converter_MessageUnexpectedEntryKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Failed to find parent post for comment &apos;{0}&apos;.
        /// </summary>
        internal static string Converter_OrphanedComment {
            get {
                return ResourceManager.GetString("Converter_OrphanedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing BlogML to {0}.
        /// </summary>
        internal static string Converter_WritingBlogML {
            get {
                return ResourceManager.GetString("Converter_WritingBlogML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger2BlogML {0}.{1:00} {2}
        ///http://blogger2blogml.codeplex.com/.
        /// </summary>
        internal static string Program_Banner {
            get {
                return ResourceManager.GetString("Program_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed: {0}.
        /// </summary>
        internal static string Program_Exception {
            get {
                return ResourceManager.GetString("Program_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it isn&apos;t obvious how to fix this error please report it at:
        ///http://blogger2blogml.codeplex.com/workitem/list/basic.
        /// </summary>
        internal static string Program_ReportError {
            get {
                return ResourceManager.GetString("Program_ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Blogger2BlogML &lt;blogger export file&gt; &lt;blogml file to create&gt;.
        /// </summary>
        internal static string Program_Usage {
            get {
                return ResourceManager.GetString("Program_Usage", resourceCulture);
            }
        }
    }
}
